stages:
  - common-style
  - common-quality
  - common-test
  - package

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  DOCKER_DRIVER: overlay2
  CODESTYLE_VERSION: "6.4.20.0"
  DEFAULT_SW_VERSION: "v6.2.0"
  PLUGIN_NAME: 'UnzerPayment6'
  COMPOSER_HOME: '/var/www/html/.composer'
  COMPOSER_COMMAND: "/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"

include:
  - project: 'kellerkinder/pipeline-common'
    file:
      - '/plugin/codestyle.yml'
      - '/plugin/phpstan/k10r/sw-64.yml'
      - '/plugin/phpstan/k10r/sw-65.yml'
      - '/plugin/phpstan/sw/sw-64.yml'
      - '/plugin/phpstan/sw/sw-65.yml'
      - '/plugin/install/sw-64.yml'
      - '/plugin/install/sw-65.yml'
      - '/plugin/build-package.yml'