stages:
  - common-style
  - common-quality
  - common-test
  - common-package

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  DOCKER_DRIVER: overlay2
  COMPOSER_HOME: '/var/www/html/.composer'
  COMPOSER_COMMAND: "/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"
  CODESTYLE_VERSION: "6.4.20.0"
  DEFAULT_SW_VERSION: "v6.2.0"

include:
  - project: 'kellerkinder/pipeline-common'
    file:
      - '/plugin/codestyle.yml'
      - '/plugin/phpstan/k10r/sw-64.yml'
      - '/plugin/phpstan/k10r/sw-65.yml'
      - '/plugin/phpstan/sw/sw-64.yml'
      - '/plugin/phpstan/sw/sw-65.yml'
      - '/plugin/install/sw-64.yml'
      - '/plugin/install/sw-65.yml'
      - '/plugin/build-package.yml'

before_script:
  - curl https://getcomposer.org/download/2.4.4/composer.phar -o /var/www/html/composer
  - chmod +x /var/www/html/composer
  - ${COMPOSER_COMMAND}
  - cp -r ${CI_PROJECT_DIR} /var/www/html/custom/plugins/${CI_PROJECT_NAME}
